name: sohasms
description: "A SMS forwarder for native uses"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  flex_color_scheme:
  getwidget: ^4.0.0
  dropdown_search:
  flutter_chat_ui: ^1.6.15
  flutter_chat_bubble: ^2.0.2
  flutter_contacts: ^1.1.9+2
  get_storage:
  fluttertoast:
  background_sms:
  persian_number_utility:
  flutter_background_service: ^5.0.10
  flutter_local_notifications:
  permission_handler:
  flutter_isolate: ^2.1.0
  sms_advanced:
    git:
      url: https://github.com/EddieKamau/sms_advanced.git
      ref: master
#  flutter_sms:
#    git:
#      url: https://github.com/fluttercommunity/flutter_sms.git
#      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  fonts:
    - family: yekan
      fonts:
        - asset: fonts/BYekan+_0.ttf
        - asset: fonts/BYekan+ Bold.ttf
          weight: 700
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
